# This module is automatically generated by autogen.sh. DO NOT EDIT.

from . import _Clients


class _Client(_Clients):
    _type = "clients"
    _icon_dir = "resources/clients"


class Neom(_Client):
    _icon = "neom.png"


# Aliases
