# This module is automatically generated by autogen.sh. DO NOT EDIT.

from . import _Adobe


class MarketingCloud(_Adobe):
    _type = "analytics"
    _icon_dir = "resources/adobe/"


class Analytics(MarketingCloud):
    _icon = "adobe-analytics.png"


class Launch(MarketingCloud):
    _icon = "adobe-launch.png"


# Aliases
AA = Analytics