# This module is automatically generated by autogen.sh. DO NOT EDIT.

from . import _Saas


class _TagManagement(_Saas):
    _type = "tagmanagement"
    _icon_dir = "resources/saas/tagmanagement"


class Tealium(_TagManagement):
    _icon = "tealium.png"


# Aliases
